import { LiveSession, ScheduleItem, StartingSoonSession } from "./types";

export const TAGS = ["雑談", "ゲーム", "歌枠", "英語", "参加型"];

export const STARTING_SOON_SESSIONS: StartingSoonSession[] = [
  {
    id: 1,
    vtuber: "夏色まつり",
    title: "歌枠 - リクエスト受付中！一緒に歌おう",
    thumbnail: "/image/thumbnail/thumbnail_1.png",
    startsInSeconds: 25 * 60,
    slotsTotal: 15,
    slotsLeft: 4,
    participationType: "Lottery",
    isSubscribed: false,
    tags: ["歌枠", "参加型"],
    description: "リクエスト受付中の歌枠！好きな曲をコメントで教えてください。みんなで楽しもう！",
    duration: "約120分",
    glowColor: "rgba(236,72,153,0.4)",
  },
  {
    id: 2,
    vtuber: "星野るな",
    title: "English Learning - Let's Study Together!",
    thumbnail:
      "https://images.unsplash.com/photo-1763932838090-8de19d424c11?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxhbmltZSUyMGdpcmwlMjB5ZWxsb3clMjBzcGFya2xlJTIwY29sb3JmdWwlMjBpbGx1c3RyYXRpb258ZW58MXx8fHwxNzcyMTY5NTM2fDA&ixlib=rb-4.1.0&q=80&w=1080",
    startsInSeconds: 90 * 60,
    slotsTotal: 12,
    slotsLeft: 3,
    participationType: "First-come",
    isSubscribed: true,
    tags: ["英語", "参加型"],
    description: "一緒に英語を練習しましょう！初心者大歓迎。日常英会話・TOEIC対策など。",
    duration: "約75分",
    glowColor: "rgba(245,158,11,0.4)",
  },
  {
    id: 3,
    vtuber: "赤井はあと",
    title: "料理配信 - 視聴者とメニュー相談！何作ろう？",
    thumbnail: "/image/thumbnail/thumbnail_3.png",
    startsInSeconds: 165 * 60,
    slotsTotal: 10,
    slotsLeft: 8,
    participationType: "Members-only",
    isSubscribed: true,
    tags: ["雑談", "参加型"],
    description: "今日のメニューをみんなで決めよう！リクエストも受付中。",
    duration: "約90分",
    glowColor: "rgba(16,185,129,0.4)",
  },
];

export const LIVE_NOW_SESSIONS: LiveSession[] = [
  {
    id: 10,
    vtuber: "ときのそら",
    title: "深夜のチル雑談 - あなたの話を聞かせて",
    thumbnail:
      "https://images.unsplash.com/photo-1764438234488-af3923faf0cd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxhbmltZSUyMGNoYXJhY3RlciUyMGJsdWUlMjBnbG93aW5nJTIwYXJ0d29yayUyMGRpZ2l0YWx8ZW58MXx8fHwxNzcyMTY5NTM1fDA&ixlib=rb-4.1.0&q=80&w=1080",
    viewers: 234,
    slotsTotal: 10,
    slotsLeft: 2,
    participationType: "First-come",
    isSubscribed: true,
    tags: ["雑談"],
    description: "深夜のゆったりとした雑談配信。視聴者の皆さんと一緒に話しましょう！",
    duration: "約60分",
    userHistory: { totalParticipations: 12, lastParticipation: "2026.02.20" },
  },
  {
    id: 11,
    vtuber: "白上フブキ",
    title: "視聴者参加型ゲーム配信 - 一緒に遊ぼう！",
    thumbnail:
      "https://images.unsplash.com/photo-1551361976-702ef47a922d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxhbmltZSUyMGdpcmwlMjByZWQlMjBvcmFuZ2UlMjBicmlnaHQlMjB2aXZpZCUyMGFydHdvcmt8ZW58MXx8fHwxNzcyMTY5NTM5fDA&ixlib=rb-4.1.0&q=80&w=1080",
    viewers: 189,
    slotsTotal: 8,
    slotsLeft: 0,
    participationType: "Lottery",
    isSubscribed: false,
    tags: ["ゲーム"],
    description: "みんなで一緒にゲームを楽しもう！初心者大歓迎！",
    duration: "約90分",
  },
];

const TODAY_SCHEDULE: ScheduleItem[] = [
  {
    id: 20,
    time: "14:00",
    vtuber: "田中ユキ",
    title: "Afternoon Tea & Talk",
    thumbnail: "https://images.unsplash.com/photo-1696360085643-2fc69d679bdb?w=80&h=80&fit=crop",
    isMembersOnly: false,
    isLottery: false,
    hasReserved: true,
    tags: ["雑談"],
  },
  {
    id: 21,
    time: "16:30",
    vtuber: "宮本さくら",
    title: "お絵かき練習配信",
    thumbnail: "https://images.unsplash.com/photo-1673047233994-78df05226bfc?w=80&h=80&fit=crop",
    isMembersOnly: false,
    isLottery: false,
    hasReserved: false,
    tags: ["雑談"],
  },
  {
    id: 22,
    time: "18:00",
    vtuber: "星野るな",
    title: "Language Learning Hour",
    thumbnail: "https://images.unsplash.com/photo-1763932838090-8de19d424c11?w=80&h=80&fit=crop",
    isMembersOnly: true,
    isLottery: false,
    hasReserved: true,
    tags: ["英語"],
  },
  {
    id: 23,
    time: "20:00",
    vtuber: "エマ・ウィリアムズ",
    title: "Game Tournament",
    thumbnail: "https://images.unsplash.com/photo-1551361976-702ef47a922d?w=80&h=80&fit=crop",
    isMembersOnly: false,
    isLottery: true,
    hasReserved: false,
    tags: ["ゲーム"],
  },
  {
    id: 24,
    time: "21:00",
    vtuber: "宮本さくら",
    title: "Night Gaming Session",
    thumbnail: "https://images.unsplash.com/photo-1597407038730-7ea64647fc89?w=80&h=80&fit=crop",
    isMembersOnly: false,
    isLottery: false,
    hasReserved: false,
    tags: ["ゲーム"],
  },
];

export const SCHEDULE_BY_DATE: Record<string, ScheduleItem[]> = {
  "02.27": TODAY_SCHEDULE,
  "02.28": [
    {
      id: 30,
      time: "15:00",
      vtuber: "エマ・ウィリアムズ",
      title: "Art Workshop",
      thumbnail: "https://images.unsplash.com/photo-1551361976-702ef47a922d?w=80&h=80&fit=crop",
      isMembersOnly: true,
      isLottery: false,
      hasReserved: false,
      tags: ["雑談"],
    },
    {
      id: 31,
      time: "19:00",
      vtuber: "田中ユキ",
      title: "Evening Chat",
      thumbnail: "https://images.unsplash.com/photo-1696360085643-2fc69d679bdb?w=80&h=80&fit=crop",
      isMembersOnly: false,
      isLottery: false,
      hasReserved: false,
      tags: ["雑談"],
    },
  ],
  "03.01": [
    {
      id: 40,
      time: "13:00",
      vtuber: "宮本さくら",
      title: "Lunch Sketch Stream",
      thumbnail: "https://images.unsplash.com/photo-1673047233994-78df05226bfc?w=80&h=80&fit=crop",
      isMembersOnly: false,
      isLottery: false,
      hasReserved: false,
      tags: ["雑談"],
    },
    {
      id: 41,
      time: "20:00",
      vtuber: "夏色まつり",
      title: "リクエスト歌枠",
      thumbnail: "https://images.unsplash.com/photo-1763932838090-8de19d424c11?w=80&h=80&fit=crop",
      isMembersOnly: false,
      isLottery: true,
      hasReserved: false,
      tags: ["歌枠"],
    },
  ],
};
