import { LiveSession, StartingSoonSession } from "./types";

export const TAGS = ["雑談", "ゲーム", "歌枠", "英語", "参加型"];

export const STARTING_SOON_SESSIONS: StartingSoonSession[] = [
  {
    id: "1",
    vtuber: "夜城ルミナ",
    title: "【侵食エンド世界】リスナー参加型サバイバル建国計画",
    thumbnail: "/image/thumbnail/thumbnail_1.png",
    startsInSeconds: 25 * 60,
    slotsTotal: 15,
    slotsLeft: 4,
    participationType: "Lottery",
    isSubscribed: false,
    tags: ["ゲーム", "参加型"],
    description: "エンドに侵食された異変ワールドで、リスナーと協力しながら文明を再建する長期マイクラ企画。",
    duration: "約120分",
    glowColor: "rgba(236,72,153,0.4)",
  },
  {
    id: "2",
    vtuber: "焔角リゼル",
    title: "【完全初見】DARK SOULS 制覇への血路",
    thumbnail: "/image/thumbnail/thumbnail_2.png",
    startsInSeconds: 90 * 60,
    slotsTotal: 12,
    slotsLeft: 3,
    participationType: "First-come",
    isSubscribed: true,
    tags: ["ゲーム"],
    description: "死にゲー未経験の悪魔系VTuberが、視聴者の助言と悲鳴に包まれながらダクソを本気攻略。",
    duration: "約75分",
    glowColor: "rgba(245,158,11,0.4)",
  },
  {
    id: "3",
    vtuber: "白雪ノエルナ",
    title: "まったり夜カフェ雑談",
    thumbnail: "/image/thumbnail/thumbnail_3.png",
    startsInSeconds: 165 * 60,
    slotsTotal: 10,
    slotsLeft: 8,
    participationType: "Members-only",
    isSubscribed: true,
    tags: ["雑談"],
    description: "コーヒー片手に、日常の話や最近の悩み、裏話をゆるく語る定期リラックス配信。",
    duration: "約90分",
    glowColor: "rgba(16,185,129,0.4)",
  },
];

export const LIVE_NOW_SESSIONS: LiveSession[] = [
  {
    id: "10",
    vtuber: "陽葵エルナ",
    title: "【今日から話せる】初心者向け英会話ライブレッスン",
    thumbnail: "/image/thumbnail/thumbnail_5.png",
    viewers: 234,
    slotsTotal: 10,
    slotsLeft: 2,
    participationType: "First-come",
    isSubscribed: true,
    tags: ["英語", "参加型"],
    description: "発音・リアルな会話例・そのまま使えるテンプレをセットで学び、コメント参加型でその場アウトプットまでやる英語配信。",
    duration: "約60分",
    userHistory: { totalParticipations: 12, lastParticipation: "2026.02.20" },
  },
  {
    id: "11",
    vtuber: "星宮ポラリス ＆ 桜庭メイカ",
    title: "視聴者参加型！ガチレース耐久",
    thumbnail: "/image/thumbnail/thumbnail_4.png",
    viewers: 189,
    slotsTotal: 8,
    slotsLeft: 0,
    participationType: "Lottery",
    isSubscribed: false,
    tags: ["ゲーム", "参加型"],
    description: "フレンド戦で視聴者と本気レース、ポイント制で罰ゲームありの白熱コラボ配信。",
    duration: "約90分",
  },
];
